name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Run test coverage
        run: |
          nix develop --command just ci-test-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: cobertura.xml
